### ISSUE TITLE
Mint Beta

### ISSUE THREAD

**Issue by deepika05** [mddub/mint-tags-display#10]
hi.. any chance you could make this work on the new beta interface? they are going to switch over to the new interface here shortly. thanks!

**Comment by originaltexter** [comment]
I'll second this. Beta is out now and I can't see any tags anymore. I'd love if the creator is able to modify this to work again! Thank you.

**Comment by deepika05** [comment]
does not seem to be working on my end. i'm permanently on the new mint interface now, btw

**Comment by originaltexter** [comment]
I needed to reinstall the plug-in to get it to work. Working fine for me now.

**Comment by deepika05** [comment]
no dice. removed the script and installed it again. still nothing

**Comment by originaltexter** [comment]
This is where I reinstalled from.
https://greasyfork.org/en/scripts/12523-mint-com-tags-display
