### ISSUE TITLE
Not Working on Updated Mint Site

### ISSUE THREAD

**Issue by herikwebb** [mddub/mint-tags-display#13]
This does not seem to be working on the latest version of the mint site. Details below. 

Browser: Firefox v111.0
Extension: Greasemonkey
mint-tags-display v2.0.0

Issue: Tags not displaying in the transactions list (screenshot below)

![image](https://user-images.githubusercontent.com/1936533/226506483-f1c8bb92-2c13-4f7d-96c6-b1f5c5aed831.png)

**Comment by annabunches** [comment]
I don't know whether this project is still active or whether you still even want this fix, but I have filed https://github.com/mddub/mint-tags-display/pull/14 to fix this issue. It's only a one-line change if you want to apply it manually in greasemonkey.
