### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by JohnLivermore** [mddub/mint-tags-display#3]
I just installed this to Chrome 53, but even after restarting Chrome, I am not seeing my tags in the Transactions view.  Is this still working?

**Comment by misterbrandt** [comment]
Mint has been rolling out a new URL - was mint.com, is now mint.intuit.com
If you can edit your copy of the script - revise line 3 to read:

// @include     https://mint.intuit.com/*

**Comment by JohnLivermore** [comment]
Yes, that worked thanks!  Just a hint to anyone else, if you edit the file directly through Tampermonkey, be sure to hit save after you make the above changes.  Ow, it won't take.

**Comment by mddub** [comment]
Thanks for reporting. Fixed in #4. Pull requests are welcome, of course :)

If you installed via the README or Greasyfork and left the `updateURL` intact, your local copy of the script should automatically pick up this change.
