### ISSUE TITLE
Script is enabled but not working

### ISSUE THREAD

**Issue by GaryFinley** [mddub/mint-tags-display#8]
I have Greasemonkey loaded in Firefox and the mint tags script is installed and enabled, but no tags show up in the categories even after rebooting.  Am I missing a step?

Edit:  I used Chrome + Tampermonkey and it worked just fine.  So that's good enough for now.  
Thanks!

**Comment by mmorey** [comment]
I can confirm @GaryFinley findings, I got it to work in Chrome but not in Firefox 67.0b4.
